language: java

jdk:
  - oraclejdk8

install: mvn clean verify site -Dlinkcheck.skip=true -Dmaven.javadoc.skip=true
             -Dpmd.skip=true -Dfindbugs.skip=true

after_success:
  - mvn -Ptravis clean test jacoco:report coveralls:report
