language: java

jdk:
  - oraclejdk8

install: mvn --batch-mode clean verify site

after_success:
  - mvn --batch-mode clean test org.jacoco:jacoco-maven-plugin:report org.eluder.coveralls:coveralls-maven-plugin:report
